# .github/workflows/backup.yml
name: Database Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Backup DB
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            docker exec ai-passive-income-db-1 mysqldump -u wordpress -pwordpress wordpress > backup.sql
            gzip backup.sql